"""
Integration tests for PDF MCP tool.

Tests:
- generate_and_upload_pdf: create PDF from HTML and upload to volume
"""

import logging

import pytest
from databricks.sdk.service.catalog import VolumeType

from databricks_mcp_server.tools.pdf import generate_and_upload_pdf
from databricks_mcp_server.tools.volume_files import manage_volume_files
from tests.test_config import TEST_RESOURCE_PREFIX

logger = logging.getLogger(__name__)

# Deterministic names for tests
PDF_FILENAME = f"{TEST_RESOURCE_PREFIX}test.pdf"
PDF_VOLUME_NAME = f"{TEST_RESOURCE_PREFIX}pdf_vol"


@pytest.fixture(scope="module")
def pdf_volume(workspace_client, test_catalog: str, pdf_schema: str):
    """Create a volume for PDF tests."""
    volume_name = PDF_VOLUME_NAME

    # Create volume if not exists
    try:
        workspace_client.volumes.create(
            catalog_name=test_catalog,
            schema_name=pdf_schema,
            name=volume_name,
            volume_type=VolumeType.MANAGED,
        )
        logger.info(f"Created volume: {volume_name}")
    except Exception as e:
        if "already exists" in str(e).lower():
            logger.info(f"Volume already exists: {volume_name}")
        else:
            raise

    yield volume_name

    # Cleanup
    try:
        workspace_client.volumes.delete(f"{test_catalog}.{pdf_schema}.{volume_name}")
        logger.info(f"Cleaned up volume: {volume_name}")
    except Exception as e:
        logger.warning(f"Failed to cleanup volume: {e}")


@pytest.mark.integration
class TestGenerateAndUploadPdf:
    """Tests for generate_and_upload_pdf tool."""

    def test_generate_simple_pdf(
        self,
        test_catalog: str,
        pdf_schema: str,
        pdf_volume: str,
    ):
        """Should generate a PDF from HTML and upload to volume."""
        html_content = """
        <html>
        <head>
            <style>
                body { font-family: Arial, sans-serif; margin: 40px; }
                h1 { color: #1a73e8; }
                p { line-height: 1.6; }
                ul { margin-top: 10px; }
            </style>
        </head>
        <body>
            <h1>Test PDF Document</h1>
            <p>This is a test paragraph with <b>bold</b> and <i>italic</i> text.</p>
            <p>Generated by MCP integration tests.</p>
            <h2>Features Tested</h2>
            <ul>
                <li>HTML to PDF conversion</li>
                <li>CSS styling support</li>
                <li>Upload to Unity Catalog volume</li>
            </ul>
        </body>
        </html>
        """

        result = generate_and_upload_pdf(
            html_content=html_content,
            filename=PDF_FILENAME,
            catalog=test_catalog,
            schema=pdf_schema,
            volume=pdf_volume,
            folder="test_pdfs",
        )

        logger.info(f"Generate PDF result: {result}")

        assert result.get("success"), f"PDF generation failed: {result}"
        assert result.get("volume_path"), "Should return volume path"
        assert PDF_FILENAME in result["volume_path"]

        # Verify file exists by listing the folder
        volume_path = f"/Volumes/{test_catalog}/{pdf_schema}/{pdf_volume}/test_pdfs"
        list_result = manage_volume_files(
            action="list",
            volume_path=volume_path,
        )

        logger.info(f"List volume result: {list_result}")

        # Check that our PDF is in the list
        files = list_result.get("files", [])
        file_names = [f.get("name", "") for f in files]
        assert PDF_FILENAME in file_names, f"PDF should exist in volume: {file_names}"

    def test_generate_pdf_with_complex_html(
        self,
        test_catalog: str,
        pdf_schema: str,
        pdf_volume: str,
    ):
        """Should handle complex HTML with tables and images."""
        html_content = """
        <html>
        <head>
            <style>
                table { border-collapse: collapse; width: 100%; margin: 20px 0; }
                th, td { border: 1px solid #ddd; padding: 12px; text-align: left; }
                th { background-color: #4CAF50; color: white; }
                tr:nth-child(even) { background-color: #f2f2f2; }
            </style>
        </head>
        <body>
            <h1>Data Report</h1>
            <table>
                <tr>
                    <th>ID</th>
                    <th>Name</th>
                    <th>Value</th>
                    <th>Status</th>
                </tr>
                <tr>
                    <td>1</td>
                    <td>Item A</td>
                    <td>$100.00</td>
                    <td>Active</td>
                </tr>
                <tr>
                    <td>2</td>
                    <td>Item B</td>
                    <td>$250.50</td>
                    <td>Pending</td>
                </tr>
                <tr>
                    <td>3</td>
                    <td>Item C</td>
                    <td>$75.25</td>
                    <td>Complete</td>
                </tr>
            </table>
            <p><em>Report generated automatically by MCP tests.</em></p>
        </body>
        </html>
        """

        result = generate_and_upload_pdf(
            html_content=html_content,
            filename="complex_report.pdf",
            catalog=test_catalog,
            schema=pdf_schema,
            volume=pdf_volume,
            folder="reports",
        )

        logger.info(f"Generate complex PDF result: {result}")

        assert result.get("success"), f"PDF generation failed: {result}"
        assert result.get("volume_path"), "Should return volume path"
        assert "reports" in result["volume_path"]

    def test_generate_pdf_minimal_html(
        self,
        test_catalog: str,
        pdf_schema: str,
        pdf_volume: str,
    ):
        """Should handle minimal HTML content."""
        result = generate_and_upload_pdf(
            html_content="<html><body><p>Minimal content</p></body></html>",
            filename="minimal.pdf",
            catalog=test_catalog,
            schema=pdf_schema,
            volume=pdf_volume,
        )

        logger.info(f"Generate minimal PDF result: {result}")

        assert result.get("success"), f"PDF generation failed: {result}"

    def test_generate_pdf_nested_folder(
        self,
        test_catalog: str,
        pdf_schema: str,
        pdf_volume: str,
    ):
        """Should create PDF in nested folder path."""
        result = generate_and_upload_pdf(
            html_content="<html><body>Nested folder test</body></html>",
            filename="nested.pdf",
            catalog=test_catalog,
            schema=pdf_schema,
            volume=pdf_volume,
            folder="level1/level2/level3",
        )

        logger.info(f"Generate nested PDF result: {result}")

        assert result.get("success"), f"PDF generation failed: {result}"
        assert "level1/level2/level3" in result.get("volume_path", "")

    def test_generate_pdf_special_characters_filename(
        self,
        test_catalog: str,
        pdf_schema: str,
        pdf_volume: str,
    ):
        """Should handle special characters in filename (within limits)."""
        # Use underscores and hyphens which are safe
        result = generate_and_upload_pdf(
            html_content="<html><body>Special chars test</body></html>",
            filename="report_2024-01-15_final.pdf",
            catalog=test_catalog,
            schema=pdf_schema,
            volume=pdf_volume,
        )

        logger.info(f"Generate special chars PDF result: {result}")

        assert result.get("success"), f"PDF generation failed: {result}"
